project: mongodb-database
database:
  engine: mongodb
  connection_url: ${MONGODB_URI}
  tls: ${MONGODB_TLS}
  tls_ca_file: ${MONGODB_TLS_CA_FILE}
  scripts_path: mongo
  version_collection: controle_versoes
  execution_order:
    - file: colecoes.json
      mode: on_change
